# Generated by Django 6.0.6 on 2026-06-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_merge_0014_profile_image_0016_review_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
