# Generated by Django 6.0.6 on 2026-06-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_profile_image"),
        ("main", "0018_remove_profile_image"),
    ]

    operations = []
