# Generated by Django 6.0.6 on 2026-06-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_merge_0014_profile_image_0018_remove_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="descirptions",
        ),
        migrations.RemoveField(
            model_name="place",
            name="has_partition",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
    ]
